/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.layout;

import java.awt.event.KeyEvent;

/**
 *
 * @author Iora
 */
public class FrameCadastros extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastros
     */
    public FrameCadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlunos = new javax.swing.JButton();
        btnLivros = new javax.swing.JButton();
        btnCidades = new javax.swing.JButton();
        btnSessoes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnMapas = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_clientes.png"))); // NOI18N
        btnAlunos.setText("Cadastro de Alunos");
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        btnAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAlunosKeyPressed(evt);
            }
        });
        getContentPane().add(btnAlunos);
        btnAlunos.setBounds(60, 120, 210, 70);

        btnLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_livros.png"))); // NOI18N
        btnLivros.setText("Cadastro de Livros");
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosActionPerformed(evt);
            }
        });
        btnLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLivrosKeyPressed(evt);
            }
        });
        getContentPane().add(btnLivros);
        btnLivros.setBounds(320, 120, 200, 70);

        btnCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_cidade.png"))); // NOI18N
        btnCidades.setText("Cadastro de Cidades");
        btnCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidadesActionPerformed(evt);
            }
        });
        btnCidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCidadesKeyPressed(evt);
            }
        });
        getContentPane().add(btnCidades);
        btnCidades.setBounds(320, 280, 200, 70);

        btnSessoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_secoes.png"))); // NOI18N
        btnSessoes.setText("Cadastro de Seções");
        btnSessoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessoesActionPerformed(evt);
            }
        });
        btnSessoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSessoesKeyPressed(evt);
            }
        });
        getContentPane().add(btnSessoes);
        btnSessoes.setBounds(580, 280, 210, 70);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_user.png"))); // NOI18N
        btnUsuarios.setText("Cadastro de Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        btnUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUsuariosKeyPressed(evt);
            }
        });
        getContentPane().add(btnUsuarios);
        btnUsuarios.setBounds(60, 280, 210, 70);

        btnMapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_mapa_botao.png"))); // NOI18N
        btnMapas.setText("Cadastro de Mapas");
        btnMapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapasActionPerformed(evt);
            }
        });
        btnMapas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMapasKeyPressed(evt);
            }
        });
        getContentPane().add(btnMapas);
        btnMapas.setBounds(580, 120, 210, 70);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_sair_int.png"))); // NOI18N
        btnSair.setText("Voltar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSairKeyPressed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(60, 410, 130, 55);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_cadastros.png"))); // NOI18N
        jLabel1.setText("Cadastros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 20, 210, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/icone_fundo_azul.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 910, 520);

        setSize(new java.awt.Dimension(916, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSessoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessoesActionPerformed
       FrameSessoes SS = new FrameSessoes();
       SS.setLocationRelativeTo(null);
       SS.setVisible(true);
    }//GEN-LAST:event_btnSessoesActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidadesActionPerformed
       FrameCidade FC = new FrameCidade();
       FC.setLocationRelativeTo(null);
       FC.setVisible(true);
    }//GEN-LAST:event_btnCidadesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
      FrameUsuario US = new FrameUsuario();
       US.setLocationRelativeTo(null);
       US.setVisible(true); 
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
    FrameCliente FCl = new FrameCliente();
       FCl.setLocationRelativeTo(null);
       FCl.setVisible(true);
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrosActionPerformed
        FrameLivros LV = new FrameLivros();
       LV.setLocationRelativeTo(null);
       LV.setVisible(true);
    }//GEN-LAST:event_btnLivrosActionPerformed

    private void btnMapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapasActionPerformed
       FrameMapa FM = new FrameMapa();
       FM.setLocationRelativeTo(null);
       FM.setVisible(true); 
    }//GEN-LAST:event_btnMapasActionPerformed

    private void btnSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSairKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnSair.doClick();
    }//GEN-LAST:event_btnSairKeyPressed

    private void btnAlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAlunosKeyPressed
     if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnAlunos.doClick();
    }//GEN-LAST:event_btnAlunosKeyPressed

    private void btnSessoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSessoesKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnSessoes.doClick();
    }//GEN-LAST:event_btnSessoesKeyPressed

    private void btnUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUsuariosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnUsuarios.doClick();
    }//GEN-LAST:event_btnUsuariosKeyPressed

    private void btnLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLivrosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnLivros.doClick();
    }//GEN-LAST:event_btnLivrosKeyPressed

    private void btnMapasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMapasKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnMapas.doClick();
    }//GEN-LAST:event_btnMapasKeyPressed

    private void btnCidadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCidadesKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) btnCidades.doClick();
    }//GEN-LAST:event_btnCidadesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnCidades;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnMapas;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSessoes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
